- name: demo on conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
  - name: live or not
    ansible.builtin.debug:
      msg: "Yes, this is LIVE session"
    when: IS_LIVE