- name: conditions on loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packaegs
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - zip