- name: demo on filters
  hosts: local
  connection: local
  vars:
    Topics: DevOps, Linux, Ansible, AWS
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "{{ GREETING | default('Sivakumar Reddy M') }}"

  - name: 
    ansible.builtin.debug:
      msg: "{{ Topics | split(',') }}"